features/9-popupmodaltowatchtrailerjs
jeffcela/Rotten_Trailers pull request #37
Opened 2021-08-07 22:36 UTC by ptriv1

This is what I did so far on the modal branch, but now I really need some help with getting this to function.  I found a separate YouTube iFrame Player API: https://developers.google.com/youtube/player_parameters .  We need to use the video ID so we can get the video to play when we click on Watch Trailer.  I wasn't sure how to refine my parameters to pull only trailers, so this needs some refinement.

2021-08-07 23:16 UTC, KatsuMatsushita requested changes
Take out the callYouTube(); function call on line 50, as that should be unnecessary aside from testing.

2021-08-07 23:18 UTC, ptriv1 commented
The callYouTube(); is removed.

2021-08-07 23:51 UTC, KatsuMatsushita approved these changes

2021-08-08 00:10 UTC, jeffcela approved these changes

2021-08-08 00:11 UTC, merged