Feature/18 css style aside
jeffcela/Rotten_Trailers pull request #38
Opened 2021-08-08 18:54 UTC by Hannahdlewis

Updated html and css for the aside recent search  container/element/feature.

HTML-updated search button icon for the search feature
HTML-added additional li, to add up to 5 total searches
HTML-updated name from 'recent' to 'recent search'
HTML-updated color and font for 'recent search' <h5>
CSS-adding padding for searches buttons

2021-08-08 19:15 UTC, KatsuMatsushita requested changes
Please see if the button effects from the previous version can be saved
`class="waves-effect waves-light btn"`

2021-08-08 19:15 UTC, KatsuMatsushita commented on search.html
> +                    <button id="btn-search" class="btn btn-search"><i title="Search" class="material-icons">search</i></button>
Can we put the waves-effect and waves-light classes back onto the button here on line 40?

2021-08-08 20:22 UTC, Hannahdlewis commented
updated btn to reflect wave affect
added <p> tag for director to results card div

2021-08-08 21:36 UTC, KatsuMatsushita approved these changes

2021-08-08 21:36 UTC, KatsuMatsushita approved these changes

2021-08-09 02:16 UTC, jeffcela approved these changes

2021-08-09 02:16 UTC, merged